/*
 * DefaultConfig.h
 *
 *  Created on: Dec 17, 2023
 *      Author: mateusz
 */

#ifndef SHARED_CONFIG_DEFAULTCONFIG_H_
#define SHARED_CONFIG_DEFAULTCONFIG_H_

#define DEFAULT_CONFIG_DIGI_ENABLE			DIGI_WIDE1
#define DEFAULT_CONFIG_VISCOUS_DELAY		1u
#define DEFAULT_CONFIG_DIGI_DELAY			4u
#define DEFAULT_CONFIG_WX_ENABLED			false
#define DEFAULT_CONFIG_WX_UMB_ENABLED		false
#define DEFAULT_CONFIG_WX_MODBUS_ENABLED 	false
#define DEFAULT_CONFIG_WX_DAVIS_ENABLED		false
#define DEFAULT_CONFIG_MS5611_OR_BME_SENSOR	false
#define DEFAULT_CONFIG_ANEMOMETER_PULSES	10u
#define DEFAULT_CONFIG_VICTRON_ENABLED		false
#define DEFAULT_CONFIG_POWERSAVE			PWSAVE_NONE
#define DEFAULT_CONFIG_GSM_ENABLED			false
#define DEFAULT_CONFIG_KEEP_GSM_ALWAYS_ON	false



#define DEFAULT_CONFIG_CALLSIGN		"N0CALL"
#define DEFAULT_CONFIG_SSID			0
#define DEFAULT_CONFIG_LATITUDE		50.000f
#define DEFAULT_CONFIG_N_OR_S		NORTH
#define DEFAULT_CONFIG_LONGITUDE	19.0000f
#define DEFAULT_CONFIG_E_OR_W		EAST
#define DEFAULT_CONFIG_DESCRIPTION	"update this text"
#define DEFAULT_CONFIG_SYMBOL		SYMBOL_WIDE1_DIGI
#define DEFAULT_CONFIG_PATH			PATH_WIDE21
#define DEFAULT_CONFIG_BEACON_START	false
#define DEFAULT_CONFIG_WX_PERIOD	5
#define DEFAULT_CONFIG_BEACON_PERIO	67
#define DEFAULT_CONFIG_WX_DOUBLE_TX	false

#define DEFAULT_CONFIG_SOURCE_TEMPERATURE	WX_SOURCE_INTERNAL
#define DEFAULT_CONFIG_SOURCE_PRESSURE		WX_SOURCE_INTERNAL
#define DEFAULT_CONFIG_SOURCE_WIND			WX_SOURCE_INTERNAL
#define DEFAULT_CONFIG_SOURCE_HUMIDITY		WX_SOURCE_INTERNAL

#define DEFAULT_CONFIG_UMB_SLAVE_CLASS			0
#define DEFAULT_CONFIG_UMB_SLAVE_ID				0
#define DEFAULT_CONFIG_UMB_CHANNEL_WINDSPEED	100
#define DEFAULT_CONFIG_UMB_CHANNEL_WINDGUSTS	100
#define DEFAULT_CONFIG_UMB_CHANNEL_WINDDIR		100
#define DEFAULT_CONDIG_UMB_CHANNEL_TEMPERATURE	100
#define DEFAULT_CONFIG_UMB_CHANNEL_QNH			100

#define DEFAULT_CONFIG_RTU_SLAVE_SPEED	9600u
#define DEFAULT_CONFIG_RTU_SLAVE_PARITY	0
#define DEFAULT_CONFIG_RTU_STOP_BITS	2
#define DEFAULT_CONFIG_RTU_FULL_WIND	false
#define DEFAULT_CONFIG_RTU_SOURCE_TEMP		1
#define DEFAULT_CONFIG_RTU_SOURCE_HUMIDITY	2
#define DEFAULT_CONFIG_RTU_SOURCE_PRESSURE	3
#define DEFAULT_CONFIG_RTU_SOURCE_WINDSPEED	4
#define DEFAULT_CONFIG_RTU_SOURCE_WINDGUST	5
#define DEFAULT_CONFIG_RTU_SOURCE_WINDDIR	6

#define DEFAULT_CONFIG_GSM_PIN			1234
#define DEFAULT_CONFIG_GSM_APNNAME		"internet"
#define DEFAULT_CONFIG_GSM_USERNAME		"username"
#define DEFAULT_CONFIG_GSM_PASSWORD		"password"
#define DEFAULT_CONFIG_GSM_API_ENABLE	false
#define DEFAULT_CONFIG_GSM_API_BASEURL	"http://78.88.56.14:8080/"
#define DEFAULT_CONFIG_APRSIS_ENABLE	true
#define DEFAULT_CONFIG_APRSIS_SERVER	"euro.aprs2.net"
#define DEFAULT_CONFIG_APRSIS_PORT		14580
#define DEFAULT_CONFIG_APRSIS_PASSCODE	16823




#endif /* SHARED_CONFIG_DEFAULTCONFIG_H_ */
