#include "StdAfx.h"
#include "windows.h"
#include "ProtocolCommBackgroundThread.h"
#include <iostream>
#include <iomanip>

ProtocolCommBackgroundThread::ProtocolCommBackgroundThread(void) : thread(0)
{
	// register all callbacks/handlers to supported protocol services
	callbackMap.insert(std::pair<uint8_t, IService *>(KISS_VERSION_AND_ID, &srvVersionAndId));

	// initialize and open serial port
	const BOOL serialInitResult = s.init();

	// create a new instance of serial RX background thread
	serialThread = new SRBT(&s, &callbackMap);

	// set serial context for all services handlers
	srvVersionAndId.setSerialContext(&s);

	// create mutex which will protect agains starting two paralell comm transactions
	threadMutex = CreateMutex(NULL, FALSE, L"ProtocolCommMutex");

	// create an event which will be generated by callback in each service handler
	serviceSyncEvent = CreateEvent(NULL, FALSE, FALSE, L"ServiceSyncEv");

	std::cout << "I = PCBT::ProtocolCommBackgroundThread" << std::endl;
	std::cout << "D = PCBT::ProtocolCommBackgroundThread, threadMutex: 0x" << std::hex 
		<< threadMutex << std::dec << std::endl;
	std::cout << "D = PCBT::ProtocolCommBackgroundThread, serviceSyncEvent: 0x" << std::hex 
		<< serviceSyncEvent << std::dec << std::endl;

}

ProtocolCommBackgroundThread::~ProtocolCommBackgroundThread(void)
{
}

BOOL ProtocolCommBackgroundThread::commVersionAndUpdateGui(HANDLE mainWindow, HANDLE editCodeplugWindow)
{
	BOOL result = false;

	DWORD threadId = 0;

	this->srvVersionAndId_context.editCodeplugWindow = editCodeplugWindow;
	this->srvVersionAndId_context.mainWindow = mainWindow;
	this->srvVersionAndId_context.getVersionAndId = &this->srvVersionAndId;
	this->srvVersionAndId_context.mutex = this->threadMutex;

	thread = CreateThread(
				NULL, 
				NULL, 
				ProtocolCommBackgroundThread_GetVersion, 
				&this->srvVersionAndId_context, 
				NULL,
				&threadId);

	std::cout << "I = PCBT::commVersionAndUpdateGui, " <<  
		std::hex << ", threadId: 0x" << threadId << std::dec << std::endl;

	if (thread != NULL)
	{
		result = true;
	}

	return result;
}

BOOL ProtocolCommBackgroundThread::getVersion(LPCSV p) 
{
	BOOL result = false;

	return result;
}

BOOL ProtocolCommBackgroundThread::commReadDidAndUpdateGui(HANDLE mainWindow, HANDLE didWindow, int didNumber) {

	return true;
}
	
BOOL ProtocolCommBackgroundThread::commRunningConfigAndUpdateGui(HANDLE mainWindow, HANDLE configWindow) {
	
	return true;
}
